### ISSUE TITLE
Upgrade to Malachite 0.4.13

### ISSUE THREAD

**Issue by mhogrefe** [tczajka/bigint-benchmark-rs#15]
Hi,

I recently received [a pull request](https://github.com/mhogrefe/malachite/pull/49) from a contributor that improved Malachite's multiplication performance. Could you rerun your benchmarks with Malachite 0.4.13?

Malachite also builds with `no-std` now.

Thanks,
Mikhail Hogrefe

**Comment by tczajka** [comment]
Done, updated to 0.4.14.
