### ISSUE TITLE
Clarifications and improvements 

### ISSUE THREAD

**Issue by matu3ba** [tczajka/bigint-benchmark-rs#2]
The benchmarks should include the **project goals (simplicity+portability[nostd] vs performance)**. 

Personally I do see memory lifetimes not as an issue, since one should use arena allocators for performance anyway.

Some other projects that could be compared, whereas libzahl would be a good candidate for a simple project (including possible benchmark extensions) are given [here](https://tiehu.is/blog/zig2.html) and personally I think [libzahl would be a candidate, because its easy to build and use](https://libs.suckless.org/libzahl/).

**Comment by tczajka** [comment]
I have added a note about no_std.

These other libraries are not Rust libraries. zig-bn is a Zig library, libzahl is a C library.
