### ISSUE TITLE
Upgrade to Malachite 0.3.0

### ISSUE THREAD

**Issue by mhogrefe** [tczajka/bigint-benchmark-rs#5]
I rewrote the fast integer multiplication for Malachite, so, according to my own benchmarks, it's a little faster now.

I've also created the meta-crate [`malachite`](https://crates.io/crates/malachite). Rather than using the `malachite-nz` dependency it's recommended to use `malachite`, which also lets you use `malachite::Natural` rather than `malachite_nz::natural::Natural`.

Could you rerun your benchmarks using this new version of Malachite?

**Comment by tczajka** [comment]
Done: upgraded to 0.3, changed to `malachite` and re-ran benchmarks.
